/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttendanceUpdate { 
    student_user_id?: number | null;
    time_in?: string | null;
    time_out?: string | null;
}

