/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttendanceOut { 
    student_user_id: number;
    time_in: string;
    time_out?: string | null;
    id: number;
    created_at: string;
    updated_at?: string | null;
}

