/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppSchemasClassUserBase } from './app-schemas-class-user-base';


export interface ClassOut { 
    name: string;
    teacher_user_id: number;
    id: number;
    teacher_user: AppSchemasClassUserBase;
    enrolled_students_count?: number | null;
}

