/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserOut } from './user-out';


export interface ClassStudentOut { 
    class_id: number;
    student_user_id: number;
    id: number;
    student_user: UserOut | null;
}

