/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserBase } from './user-base';


export interface ClassOut { 
    name: string;
    teacher_user_id: number;
    id: number;
    teacher_user: UserBase;
    enrolled_students_count?: number | null;
}

