/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppSchemasUserUserBase } from './app-schemas-user-user-base';


export interface FaceOut { 
    user_id: number;
    id: number;
    user: AppSchemasUserUserBase | null;
}

