/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppSchemasUserUserBase } from './app-schemas-user-user-base';


export interface FaceAttendanceOut { 
    student_user_id: number;
    time_in: string;
    time_out?: string | null;
    id: number;
    student_user: AppSchemasUserUserBase | null;
}

