/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppSchemasUserUserBase } from './app-schemas-user-user-base';


export interface NotificationOut { 
    user_id: number;
    title: string;
    body: string | null;
    id: number;
    is_read: boolean;
    user: AppSchemasUserUserBase | null;
    created_at: string;
    updated_at: string | null;
}

