/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttendanceOut } from './attendance-out';


export interface PageAttendanceOut { 
    items: Array<AttendanceOut>;
    total?: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
}

