/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParentStudentOut } from './parent-student-out';


export interface PageParentStudentOut { 
    items: Array<ParentStudentOut>;
    total?: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
}

