/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClassOut } from './class-out';


export interface PageClassOut { 
    items: Array<ClassOut>;
    total?: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
}

