/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationOut } from './notification-out';


export interface PageNotificationOut { 
    items: Array<NotificationOut>;
    total?: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
}

