/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClassStudentOut } from './class-student-out';


export interface PageClassStudentOut { 
    items: Array<ClassStudentOut>;
    total?: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
}

