/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const RoleEnum = {
    admin: 'admin',
    teacher: 'teacher',
    student: 'student',
    parent: 'parent'
} as const;
export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];

