/**
 * Diploma FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FaceOut } from './face-out';


export interface SearchFaceMatch { 
    face: FaceOut;
    distance: number;
}

